### ISSUE TITLE
Data not aligned with 8-byte blocksize

### ISSUE THREAD

**Issue by BeliliFahem** [hacker1024/blowfish_ecb#1]
I Always have this error : 
  `Data not aligned with 8-byte blocksize `

The encrypted messages is obtained from the backend.

**Comment by hacker1024** [comment]
Are your messages padded to be a length that's a multiple of 8? You may need something like PKCS5 padding.

**Comment by BeliliFahem** [comment]
@hacker1024 this is my pure Java encryption method 

I specify 'PKCS5Padding' padding

```
    public static byte[] encrypt(String value) {
        byte[] keyBytes = KEY.getBytes(StandardCharsets.UTF_8);
        SecretKeySpec secretKeySpec = new SecretKeySpec(keyBytes, "Blowfish");
        try {
            Cipher cipher = Cipher.getInstance("Blowfish/ECB/PKCS5Padding");
            cipher.init(Cipher.ENCRYPT_MODE, secretKeySpec);
            return cipher.doFinal(value.getBytes(StandardCharsets.UTF_8));
        } catch (
                NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | BadPaddingException | IllegalBlockSizeException e
        ) {
            e.printStackTrace();
        }
        return null;
    }
```

**Comment by hacker1024** [comment]
You'll need to implement it manually here.
It's a simple algorithm:

1. Calculate the amount of new bytes (_n_) required to get a length with a multiple of 8
2. Add _n_ to the end of your data _n_ times.

**Comment by hacker1024** [comment]
No rush, but please let me know if it solves your problem, so I can close this issue.

**Comment by BeliliFahem** [comment]
Hello @hacker1024. Yes, I solved the problem by specifying a padding at the back-end side. Thanks for your reactivity.
